version: '2.0'
services:
  shared-shopping-list-webapp:
    image: maskawanian/shared-shopping-list-webapp
    container_name: shared-shopping-list-webapp
    ports:
     - 3006:80
    environment:
      - API_ROOT=https://sharedshoppinglist-api.dsaul.ca/api/
      
  shared-shopping-list-api:
    image: maskawanian/shared-shopping-list-api
    container_name: shared-shopping-list-api
    ports:
     - 3007:5000
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=
      - MONGO_HOST=10.1.1.5
      - MONGO_PORT=3008
      - MONGO_DATABASE=shared-shopping-list
      #- FLASK_ENV=development
      #- FLASK_DEBUG=1 
     
  shared-shopping-list-mongo:
    image: mongo:4
    container_name: shared-shopping-list-mongo
    ports:
     - 3008:27017
    volumes:
     - ./data-mongo:/data/db
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=